name: flutter_movies_booking_app
description: Flutter application built with an intention to learn UI design in Flutter. This app can be considered as a prototype for movie bookin application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # https://pub.dev/packages/retrofit
  retrofit: ^1.3.1+1

  # https://pub.dev/packages/intl
  intl: ^0.16.1

  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^1.1.4

  # https://pub.dev/packages/json_serializable
  json_serializable: ^3.3.0

  # https://pub.dev/packages/json_annotation
  json_annotation: ^3.0.1

  # https://pub.dev/packages/youtube_player_flutter
  youtube_player_flutter: ^6.1.0+4

  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^1.4.1

  # https://pub.dev/packages/hive_flutter
  hive_flutter: ^0.3.0+2

  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.0.0

  # https://pub.dev/packages/qr_flutter
  qr_flutter: ^3.2.0

  # https://pub.dev/packages/fw_ticket
  fw_ticket: ^0.1.1

dev_dependencies:
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^1.3.1+9

  # https://pub.dev/packages/build_runner
  build_runner: ^1.8.1

  # https://pub.dev/packages/hive_generator
  hive_generator: ^0.7.0+2

  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.4

  # https://pub.dev/packages/flutter_automation
  flutter_automation: ^1.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/indian_cities.json
    - assets/speedometer.webp
    - assets/app_bar_logo.png
